version: '3.9'

services:
  ispconfig:
    build: .
    container_name: ispconfig
    hostname: ispconfig
    domainname: claudiomano.duckdns.org
    privileged: true
    environment:
      - LANGUAGE=C
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - HOSTNAME=server.claudiomano.duckdns.org            # see ./build/autoinstall.ini
      - HOSTNAME_EMAIL=mail.myhost.claudiomano.duckdns.org  # Hostname for email
      - DISABLED_SERVICES=rspamd unbound # disable services (apache2 clamav-daemon cron dovecot fail2ban mariadb postfix postfix pure-ftpd-mysql redis rspamd rsyslog spamassassin ssh unbound)
      - MARIADB_ROOT_PASSWORD=root
      # - REDIS_HOST=localhost
      # - POSTGREY_DELAY=300
      # - POSTGREY_MAX_AGE=35
      # - POSTGREY_TEXT="Delayed by postgrey"
      # Directory of apache vhosts to include
      # - APACHE_SUPPLEMENTARY_VHOSTS=/etc/apache2/supplementary/*.vhost
      # Apache mods to enable at start
      # - APACHE_ENABLE_MODS=macro,proxy_balancer,proxy_http
      # - APACHE_DISABLE_DEFAULT_SITE=no
      # Paths to custom ssl cert and private key
      # - SSL_CERT=
      # - SSL_CHAIN=
      # - SSL_KEY=
      # reconfigure the mariadb host at boot
      # - MYSQL_HOST=host
      # reconfigure stored password for roundcube database at start
      # - ROUNDCUBE_DB_PASSWORD=password
      # cron mail config
      # - CRON_MAILTO=
      # - CRON_MAILFROM=
    ports: [
      # "53:53", # bind
      "110", # pop3
      "995", # pop3s
      "143", # imap
      "993", # imaps
      "25", # smtp
      "587", # smtps
      "20-21", # pureftpd
      "80", "443", "8080", # web
      "22", # sshd
      "30000-30009", # pure-ftpd
    ]

    command: [ "/bin/bash" ]
    stdin_open: true
    tty: true


  # db:
  #   image: mariadb
  #   restart: always
  #   environment:
  #     MARIADB_ROOT_PASSWORD: root